stages:
  - deploy

demo:
  stage: deploy
  image: node:18
  tags:
    - dev
    - runner
  before_script:
     - mkdir -p /opt/fatmetal/front/
  script:
    - npm install
    - npm run build:dev
    - ls -l
    - rm -Rf /opt/fatmetal/front/*
    - cp -R dist/* /opt/fatmetal/front/
    - find /opt/fatmetal

  only:
    refs:
      - main
  when: manual
